
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t esthadevops2022/my-portfolio .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u esthadevops2022 --password-stdin

      - name: Push image
        run: docker push esthadevops2022/my-portfolio
