
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REPOSITORY:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,ECR_REPOSITORY
          script: |
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
            docker rm -f resume || true
            docker pull ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}
            docker run -d --name resume -p 8080:5001 ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }} 

#      - name: Build image
#        run: | 
#              docker build -t ${{ secrets.REGISTRY_USER }}/my-portfolio:${{ github.run_number }} .
#              docker build -t ${{ secrets.REGISTRY_USER }}/my-portfolio .
#      - name: Push image 
#        run: |
#            echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin
#            docker push ${{ secrets.REGISTRY_USER }}/my-portfolio:${{ github.run_number }}
#            docker push ${{ secrets.REGISTRY_USER }}/my-portfolio
# 
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH to Server
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          script: |
#                  docker rm -f resume
#                  docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USER }}/my-portfolio:${{ github.run_number }}
  
        