name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build -t esthadevops2022/my-portfolio .

    - name: push image
      run: |
        docker login -u esthadevops2022 -p ${{ secrets.REGISTRY_PASSWORD }}
        docker push esthadevops2022/my-portfolio
        