name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build -t EsthaDevops2022/my-portfolio .

    - name: push image
      run: |
       echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u esthadevops2022 --password-stdin
       docker push EsthaDevops2022/my-portfolio

        